rhoai:
  enabled: true
  namespace: redhat-ods-operator
  channel: stable-3.4
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

agentSandbox:
  enabled: true
  namespace: agent-sandbox-system
  channel: preview-0.9
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
