datasciencecluster:
  name: default-dsc
  components:
    dashboard:
      managementState: Managed
    llamastackoperator:
      managementState: Removed
    mlflowoperator:
      managementState: Managed
    trustyai:
      managementState: Managed
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: allow
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headed
      wva:
        managementState: Removed
    modelsAsService:
      managementState: Managed
    aipipelines:
      managementState: Removed
    feastoperator:
      managementState: Removed
    kueue:
      managementState: Removed
    modelregistry:
      managementState: Removed
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Removed
    trainer:
      managementState: Removed
    trainingoperator:
      managementState: Removed
    sparkoperator:
      managementState: Removed
    workbenches:
      managementState: Removed

dashboard:
  crEnabled: true
  genAiStudio: false
  modelAsService: false
  disablePerformanceMetrics: true
  disableModelCatalog: true
  disableModelRegistry: true
